version: '3.0'

services:

  # app:
  #  build:
  #   context: ..
  #  dockerfile: variables/Dockerfile
  #  ports:
  #   - "8080:8080"
  #  volumes:
  #    - ..:/app
  #   environment:
  #   - NODE_ENV=development
  #depends_on:
  #  - db

  db:
    image: mariadb:11.2.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
